// Copyright 2023 The Elastic-AI Authors.
// part of Elastic AI Search
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

#ifndef FLARE_CORE_COMMON_HALF_MATHEMATICAL_FUNCTIONS_H_
#define FLARE_CORE_COMMON_HALF_MATHEMATICAL_FUNCTIONS_H_

#include <flare/core/mathematical_functions.h>  // For the float overloads

// clang-format off
namespace flare {
// BEGIN macro definitions
#if defined(FLARE_HALF_T_IS_FLOAT) && !FLARE_HALF_T_IS_FLOAT
#define FLARE_IMPL_MATH_H_FUNC_WRAPPER(MACRO, FUNC) \
    MACRO(FUNC, flare::experimental::half_t)
#else
#define FLARE_IMPL_MATH_H_FUNC_WRAPPER(MACRO, FUNC)
#endif

#if defined(FLARE_BHALF_T_IS_FLOAT) && !FLARE_BHALF_T_IS_FLOAT
#define FLARE_IMPL_MATH_B_FUNC_WRAPPER(MACRO, FUNC) \
    MACRO(FUNC, flare::experimental::bhalf_t)
#else
#define FLARE_IMPL_MATH_B_FUNC_WRAPPER(MACRO, FUNC)
#endif

#define FLARE_IMPL_MATH_HALF_FUNC_WRAPPER(MACRO, FUNC) \
  FLARE_IMPL_MATH_H_FUNC_WRAPPER(MACRO, FUNC)          \
  FLARE_IMPL_MATH_B_FUNC_WRAPPER(MACRO, FUNC)


#define FLARE_IMPL_MATH_UNARY_FUNCTION_HALF_TYPE(FUNC, HALF_TYPE)      \
  FLARE_INLINE_FUNCTION HALF_TYPE FUNC(HALF_TYPE x) {                  \
    return static_cast<HALF_TYPE>(flare::FUNC(static_cast<float>(x))); \
  }

#define FLARE_IMPL_MATH_BINARY_FUNCTION_HALF_MIXED(FUNC, HALF_TYPE, MIXED_TYPE) \
  FLARE_INLINE_FUNCTION double FUNC(HALF_TYPE x, MIXED_TYPE y) {  \
    return flare::FUNC(static_cast<double>(x), static_cast<double>(y)); \
  } \
  FLARE_INLINE_FUNCTION double FUNC(MIXED_TYPE x, HALF_TYPE y) {  \
    return flare::FUNC(static_cast<double>(x), static_cast<double>(y)); \
  }

#define FLARE_IMPL_MATH_BINARY_FUNCTION_HALF(FUNC, HALF_TYPE)       \
  FLARE_INLINE_FUNCTION HALF_TYPE FUNC(HALF_TYPE x, HALF_TYPE y) {  \
    return static_cast<HALF_TYPE>(                                   \
        flare::FUNC(static_cast<float>(x), static_cast<float>(y))); \
  } \
  FLARE_INLINE_FUNCTION float FUNC(float x, HALF_TYPE y) {  \
    return flare::FUNC(static_cast<float>(x), static_cast<float>(y)); \
  } \
  FLARE_INLINE_FUNCTION float FUNC(HALF_TYPE x, float y) {  \
    return flare::FUNC(static_cast<float>(x), static_cast<float>(y)); \
  } \
  FLARE_IMPL_MATH_BINARY_FUNCTION_HALF_MIXED(FUNC, HALF_TYPE, double) \
  FLARE_IMPL_MATH_BINARY_FUNCTION_HALF_MIXED(FUNC, HALF_TYPE, short) \
  FLARE_IMPL_MATH_BINARY_FUNCTION_HALF_MIXED(FUNC, HALF_TYPE, unsigned short) \
  FLARE_IMPL_MATH_BINARY_FUNCTION_HALF_MIXED(FUNC, HALF_TYPE, int) \
  FLARE_IMPL_MATH_BINARY_FUNCTION_HALF_MIXED(FUNC, HALF_TYPE, unsigned int) \
  FLARE_IMPL_MATH_BINARY_FUNCTION_HALF_MIXED(FUNC, HALF_TYPE, long) \
  FLARE_IMPL_MATH_BINARY_FUNCTION_HALF_MIXED(FUNC, HALF_TYPE, unsigned long) \
  FLARE_IMPL_MATH_BINARY_FUNCTION_HALF_MIXED(FUNC, HALF_TYPE, long long) \
  FLARE_IMPL_MATH_BINARY_FUNCTION_HALF_MIXED(FUNC, HALF_TYPE, unsigned long long)


#define FLARE_IMPL_MATH_UNARY_PREDICATE_HALF(FUNC, HALF_TYPE) \
  FLARE_INLINE_FUNCTION bool FUNC(HALF_TYPE x) {              \
    return flare::FUNC(static_cast<float>(x));                \
  }

// END macros definitions


// Basic operations
    FLARE_IMPL_MATH_HALF_FUNC_WRAPPER(FLARE_IMPL_MATH_UNARY_FUNCTION_HALF_TYPE, abs)
    FLARE_IMPL_MATH_HALF_FUNC_WRAPPER(FLARE_IMPL_MATH_UNARY_FUNCTION_HALF_TYPE, fabs)
    FLARE_IMPL_MATH_HALF_FUNC_WRAPPER(FLARE_IMPL_MATH_BINARY_FUNCTION_HALF, fmod)
    FLARE_IMPL_MATH_HALF_FUNC_WRAPPER(FLARE_IMPL_MATH_BINARY_FUNCTION_HALF, remainder)
// remquo
// fma
    FLARE_IMPL_MATH_HALF_FUNC_WRAPPER(FLARE_IMPL_MATH_BINARY_FUNCTION_HALF, fmax)
    FLARE_IMPL_MATH_HALF_FUNC_WRAPPER(FLARE_IMPL_MATH_BINARY_FUNCTION_HALF, fmin)
    FLARE_IMPL_MATH_HALF_FUNC_WRAPPER(FLARE_IMPL_MATH_BINARY_FUNCTION_HALF, fdim)
// nanq
// Exponential functions
    FLARE_IMPL_MATH_HALF_FUNC_WRAPPER(FLARE_IMPL_MATH_UNARY_FUNCTION_HALF_TYPE, exp)
    FLARE_IMPL_MATH_HALF_FUNC_WRAPPER(FLARE_IMPL_MATH_UNARY_FUNCTION_HALF_TYPE, exp2)
    FLARE_IMPL_MATH_HALF_FUNC_WRAPPER(FLARE_IMPL_MATH_UNARY_FUNCTION_HALF_TYPE, expm1)
    FLARE_IMPL_MATH_HALF_FUNC_WRAPPER(FLARE_IMPL_MATH_UNARY_FUNCTION_HALF_TYPE, log)
    FLARE_IMPL_MATH_HALF_FUNC_WRAPPER(FLARE_IMPL_MATH_UNARY_FUNCTION_HALF_TYPE, log10)
    FLARE_IMPL_MATH_HALF_FUNC_WRAPPER(FLARE_IMPL_MATH_UNARY_FUNCTION_HALF_TYPE, log2)
    FLARE_IMPL_MATH_HALF_FUNC_WRAPPER(FLARE_IMPL_MATH_UNARY_FUNCTION_HALF_TYPE, log1p)
// Power functions
    FLARE_IMPL_MATH_HALF_FUNC_WRAPPER(FLARE_IMPL_MATH_BINARY_FUNCTION_HALF, pow)
    FLARE_IMPL_MATH_HALF_FUNC_WRAPPER(FLARE_IMPL_MATH_UNARY_FUNCTION_HALF_TYPE, sqrt)
    FLARE_IMPL_MATH_HALF_FUNC_WRAPPER(FLARE_IMPL_MATH_UNARY_FUNCTION_HALF_TYPE, cbrt)
    FLARE_IMPL_MATH_HALF_FUNC_WRAPPER(FLARE_IMPL_MATH_BINARY_FUNCTION_HALF, hypot)
// Trigonometric functions
    FLARE_IMPL_MATH_HALF_FUNC_WRAPPER(FLARE_IMPL_MATH_UNARY_FUNCTION_HALF_TYPE, sin)
    FLARE_IMPL_MATH_HALF_FUNC_WRAPPER(FLARE_IMPL_MATH_UNARY_FUNCTION_HALF_TYPE, cos)
    FLARE_IMPL_MATH_HALF_FUNC_WRAPPER(FLARE_IMPL_MATH_UNARY_FUNCTION_HALF_TYPE, tan)
    FLARE_IMPL_MATH_HALF_FUNC_WRAPPER(FLARE_IMPL_MATH_UNARY_FUNCTION_HALF_TYPE, asin)
    FLARE_IMPL_MATH_HALF_FUNC_WRAPPER(FLARE_IMPL_MATH_UNARY_FUNCTION_HALF_TYPE, acos)
    FLARE_IMPL_MATH_HALF_FUNC_WRAPPER(FLARE_IMPL_MATH_UNARY_FUNCTION_HALF_TYPE, atan)
    FLARE_IMPL_MATH_HALF_FUNC_WRAPPER(FLARE_IMPL_MATH_BINARY_FUNCTION_HALF, atan2)
// Hyperbolic functions
    FLARE_IMPL_MATH_HALF_FUNC_WRAPPER(FLARE_IMPL_MATH_UNARY_FUNCTION_HALF_TYPE, sinh)
    FLARE_IMPL_MATH_HALF_FUNC_WRAPPER(FLARE_IMPL_MATH_UNARY_FUNCTION_HALF_TYPE, cosh)
    FLARE_IMPL_MATH_HALF_FUNC_WRAPPER(FLARE_IMPL_MATH_UNARY_FUNCTION_HALF_TYPE, tanh)
    FLARE_IMPL_MATH_HALF_FUNC_WRAPPER(FLARE_IMPL_MATH_UNARY_FUNCTION_HALF_TYPE, asinh)
    FLARE_IMPL_MATH_HALF_FUNC_WRAPPER(FLARE_IMPL_MATH_UNARY_FUNCTION_HALF_TYPE, acosh)
    FLARE_IMPL_MATH_HALF_FUNC_WRAPPER(FLARE_IMPL_MATH_UNARY_FUNCTION_HALF_TYPE, atanh)
// Error and gamma functions
    FLARE_IMPL_MATH_HALF_FUNC_WRAPPER(FLARE_IMPL_MATH_UNARY_FUNCTION_HALF_TYPE, erf)
    FLARE_IMPL_MATH_HALF_FUNC_WRAPPER(FLARE_IMPL_MATH_UNARY_FUNCTION_HALF_TYPE, erfc)
    FLARE_IMPL_MATH_HALF_FUNC_WRAPPER(FLARE_IMPL_MATH_UNARY_FUNCTION_HALF_TYPE, tgamma)
    FLARE_IMPL_MATH_HALF_FUNC_WRAPPER(FLARE_IMPL_MATH_UNARY_FUNCTION_HALF_TYPE, lgamma)
// Nearest integer floating point functions
    FLARE_IMPL_MATH_HALF_FUNC_WRAPPER(FLARE_IMPL_MATH_UNARY_FUNCTION_HALF_TYPE, ceil)
    FLARE_IMPL_MATH_HALF_FUNC_WRAPPER(FLARE_IMPL_MATH_UNARY_FUNCTION_HALF_TYPE, floor)
    FLARE_IMPL_MATH_HALF_FUNC_WRAPPER(FLARE_IMPL_MATH_UNARY_FUNCTION_HALF_TYPE, trunc)
    FLARE_IMPL_MATH_HALF_FUNC_WRAPPER(FLARE_IMPL_MATH_UNARY_FUNCTION_HALF_TYPE, round)
// lround
// llround

    FLARE_IMPL_MATH_HALF_FUNC_WRAPPER(FLARE_IMPL_MATH_UNARY_FUNCTION_HALF_TYPE, nearbyint)
// rint
// lrint
// llrint
// Floating point manipulation functions
// frexp
// ldexp
// modf
// scalbn
// scalbln
// ilog
    FLARE_IMPL_MATH_HALF_FUNC_WRAPPER(FLARE_IMPL_MATH_UNARY_FUNCTION_HALF_TYPE, logb)
    FLARE_IMPL_MATH_HALF_FUNC_WRAPPER(FLARE_IMPL_MATH_BINARY_FUNCTION_HALF, nextafter)
// nexttoward
    FLARE_IMPL_MATH_HALF_FUNC_WRAPPER(FLARE_IMPL_MATH_BINARY_FUNCTION_HALF, copysign)
// Classification and comparison functions
// fpclassify
    FLARE_IMPL_MATH_HALF_FUNC_WRAPPER(FLARE_IMPL_MATH_UNARY_PREDICATE_HALF, isfinite)
    FLARE_IMPL_MATH_HALF_FUNC_WRAPPER(FLARE_IMPL_MATH_UNARY_PREDICATE_HALF, isinf)
    FLARE_IMPL_MATH_HALF_FUNC_WRAPPER(FLARE_IMPL_MATH_UNARY_PREDICATE_HALF, isnan)
// isnormal
    FLARE_IMPL_MATH_HALF_FUNC_WRAPPER(FLARE_IMPL_MATH_UNARY_PREDICATE_HALF, signbit)
// isgreater
// isgreaterequal
// isless
// islessequal
// islessgreater
// isunordered
// Complex number functions
#define FLARE_IMPL_MATH_COMPLEX_REAL_HALF(FUNC, HALF_TYPE) \
  FLARE_INLINE_FUNCTION HALF_TYPE FUNC(HALF_TYPE x) { return x; }

#define FLARE_IMPL_MATH_COMPLEX_IMAG_HALF(FUNC, HALF_TYPE) \
  FLARE_INLINE_FUNCTION HALF_TYPE FUNC(HALF_TYPE) { return 0; }

    FLARE_IMPL_MATH_HALF_FUNC_WRAPPER(FLARE_IMPL_MATH_COMPLEX_REAL_HALF, real)
    FLARE_IMPL_MATH_HALF_FUNC_WRAPPER(FLARE_IMPL_MATH_COMPLEX_IMAG_HALF, imag)

#undef FLARE_IMPL_MATH_COMPLEX_REAL_HALF
#undef FLARE_IMPL_MATH_COMPLEX_IMAG_HALF
#undef FLARE_IMPL_MATH_UNARY_PREDICATE_HALF
#undef FLARE_IMPL_MATH_BINARY_FUNCTION_HALF
#undef FLARE_IMPL_MATH_UNARY_FUNCTION_HALF_TYPE
#undef FLARE_IMPL_MATH_HALF_FUNC_WRAPPER
#undef FLARE_IMPL_MATH_B_FUNC_WRAPPER
#undef FLARE_IMPL_MATH_H_FUNC_WRAPPER
}  // namespace flare
// clang-format on
#endif  // FLARE_CORE_COMMON_HALF_MATHEMATICAL_FUNCTIONS_H_